name: Deploy KDA Website

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - src/**
            - gatsby-config.js
            - package.json
jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 18
            - name: Caching Gatsby
              id: gatsby-cache-build
              uses: actions/cache@v4
              with:
                  path: |
                      public
                      .cache
                      node_modules
                  key: ${{ runner.os }}-gatsby-alexhyett-site-build-${{ github.run_id }}
                  restore-keys: |
                      ${{ runner.os }}-gatsby-alexhyett-site-build-
            - name: Install dependencies
              run: yarn install
            # - name: Run Lint
            #   run: yarn run lint
            - name: Build
              run: yarn run build
            - name: Set AWS credentials
              uses: aws-actions/configure-aws-credentials@v4.1.0
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1
            - name: Deploy to S3
              run: yarn run deploy
